blank_issues_enabled: true
contact_links:
  - name: 'E-Mail'
    url: 'https://github.com/kachick/times_kachick/issues/9'
    about: 'I have no reasonable ways to contact now... my mail box is actually dead'
