blank_issues_enabled: true
contact_links:
  - name: 'E-Mail'
    url: 'https://github.com/kachick/times_kachick/issues/9'
    about: 'I have no reasonable ways to contact now... my mail box is actually dead'
  - name: 'Twitter'
    url: https://twitter.com/_kachick
    about: |
      Sorry I don't active check the twitter timeline as developer.
      I have sub-account for my hobby use(It is boardgame/tablegame!).
      Unfortunately cant't not be checked Direct Message for many spam...
